### ISSUE TITLE
💙    ____        There is no yellow color scheme.

### ISSUE THREAD

**Issue by Jakeybobble** [AntonBergaker/DoodleDigits#29]
Or any other scheme. What the heck. Let me set my background as a frog, damn it!

**Comment by AntonBergaker** [comment]
#43 Added the ability for custom themes. There's no menu for it yet, but they can be assigned by modifying the settings.json inside `%appdata%/Doodle Digits`

![image](https://github.com/AntonBergaker/DoodleDigits/assets/12459883/a1a0d433-c1d6-4d5e-aa74-2bc57390089a)

**Comment by AntonBergaker** [comment]
Fixed in #46
